### ISSUE TITLE
URLs.IMAGEWOOF train-val 

### ISSUE THREAD

**Issue by KeremTurgutlu** [fastai/imagenette#7]
```
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from fastai.vision import *
>>> path = untar_data(URLs.IMAGEWOOF)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/fastai-fork/fastai/datasets.py", line 233, in untar_data
    tarfile.open(fname, 'r:gz').extractall(dest.parent)
  File "/home/ubuntu/anaconda3/lib/python3.7/tarfile.py", line 2002, in extractall
    numeric_owner=numeric_owner)
  File "/home/ubuntu/anaconda3/lib/python3.7/tarfile.py", line 2044, in extract
    numeric_owner=numeric_owner)
  File "/home/ubuntu/anaconda3/lib/python3.7/tarfile.py", line 2114, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/home/ubuntu/anaconda3/lib/python3.7/tarfile.py", line 2163, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError, bufsize)
  File "/home/ubuntu/anaconda3/lib/python3.7/tarfile.py", line 247, in copyfileobj
    buf = src.read(bufsize)
  File "/home/ubuntu/anaconda3/lib/python3.7/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/home/ubuntu/anaconda3/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/home/ubuntu/anaconda3/lib/python3.7/gzip.py", line 482, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
>>> path = untar_data(URLs.IMAGEWOOF_320)
>>> (path/"train").ls()
[PosixPath('/home/ubuntu/.fastai/data/imagewoof-320/train/n02093754'), PosixPath('/home/ubuntu/.fastai/data/imagewoof-320/train/n02088364'), PosixPath('/home/ubuntu/.fastai/data/imagewoof-320/train/n02089973'), PosixPath('/home/ubuntu/.fastai/data/imagewoof-320/train/n02087394'), PosixPath('/home/ubuntu/.fastai/data/imagewoof-320/train/n02111889'), PosixPath('/home/ubuntu/.fastai/data/imagewoof-320/train/n02099601'), PosixPath('/home/ubuntu/.fastai/data/imagewoof-320/train/n02105641'), PosixPath('/home/ubuntu/.fastai/data/imagewoof-320/train/n02086240'), PosixPath('/home/ubuntu/.fastai/data/imagewoof-320/train/n02115641'), PosixPath('/home/ubuntu/.fastai/data/imagewoof-320/train/n02096294')]
```

Getting this error when untaring IMAGEWOOF full size. Other sizes untar without any error.

**Comment by jph00** [comment]
@KeremTurgutlu works for me. I think you have an incomplete download. Clear it our from your `.fastai` folder and try again.
